// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtULTZipdNuEMx8e3pTLLCvQ_kkeXIhY',
    appId: '1:306236633607:android:fad2652d432a79652f30a2',
    messagingSenderId: '306236633607',
    projectId: 'portal1409',
    storageBucket: 'portal1409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVV1B0OES4GAPFDhF5uaLuIsWCrLhLio',
    appId: '1:306236633607:ios:63f761200f4510d32f30a2',
    messagingSenderId: '306236633607',
    projectId: 'portal1409',
    storageBucket: 'portal1409.firebasestorage.app',
    iosBundleId: 'ru.my1409.app.portal1409',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVV1B0OES4GAPFDhF5uaLuIsWCrLhLio',
    appId: '1:306236633607:ios:63f761200f4510d32f30a2',
    messagingSenderId: '306236633607',
    projectId: 'portal1409',
    storageBucket: 'portal1409.firebasestorage.app',
    iosBundleId: 'ru.my1409.app.portal1409',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEDZs6T9Hu0455fiAeovnp6xZklsGLspk',
    appId: '1:306236633607:web:ecb66789db5787862f30a2',
    messagingSenderId: '306236633607',
    projectId: 'portal1409',
    authDomain: 'portal1409.firebaseapp.com',
    storageBucket: 'portal1409.firebasestorage.app',
    measurementId: 'G-J4L3FNLWD9',
  );
}
